### ISSUE TITLE
Markbot is saying I'm missing over half my webpage

### ISSUE THREAD

**Issue by bensullivan8** [bensullivan8/modularity-mindfulness#1]
Hi @hellachella.
I have no idea what to do with this or how it even happened. To me, the webpage that I've coded up until now is practically identical to the example, but for some reason, Markbot is being weird and telling me there's a 66% difference when I check the 608px width screenshot. The same goes for the 1000px one too. Upon further examination, it appears that for some reason Markbot just cuts off my webpage and more than 50 percent of it is missing. Any ideas? 
Here are some screenshots of what Markbot is saying...
<img width="500" alt="Screen Shot 2020-09-29 at 7 53 48 PM" src="https://user-images.githubusercontent.com/55108838/94628273-94801b80-028d-11eb-80b7-420cec90017f.png">
<img width="603" alt="Screen Shot 2020-09-29 at 7 54 16 PM" src="https://user-images.githubusercontent.com/55108838/94628278-95b14880-028d-11eb-9971-c4321f01231f.png">

**Comment by hellachella** [comment]
Strange, I'll download a zip of it and see what's up.

**Comment by hellachella** [comment]
Some hierarchy issues. 

1. Move this image into your main container: Line 31:  `<img class="banner-img" src="images/banner.svg" alt="">`
2. `main` should enclose everything below the header. The structure should be as such:
```
<body>

  <header> 
    <h1><!-- treat this <h1> as a container.-->
      <i><!-- content in ja --></i><!-- content in en -->
    </h1>
    <nav>
      <ul> 
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </nav>
  </header>

  <main>
    <img src="" alt="">
    <div class="">
      <!-- Intro info etc -->
    </div>

    <section>
      <article class="">
        <!-- content -->
      </article>

      <article class="">
        <!-- content -->
      </article>

      <article class="">
        <!-- content -->
      </article>
    </section>

  </main>

  <footer>
    <!-- content -->
  </footer>

</body>
```

**Comment by bensullivan8** [comment]
Hi @hellachella, 
Still getting the exact same issues with Markbot. Thanks for helping me better organize my code, but I implemented all of your recommendations and I'm still having trouble with Markbot. I tried restarting everything and it's not helping... Still getting the same percentages on both the 608px screenshot and 1000px screenshot.

**Comment by hellachella** [comment]
Weird. I'll redownload and look again!

**Comment by hellachella** [comment]
Ok, So I've downloaded it. I've compared them manually. There are a few fixes you need to do.

#### 1. Remove `display: flex;` from your `article a {}`. I think you are trying to push the button to the bottom. To make that happen, remove it and put display-flex on the article itself:

```
article {
  margin-bottom: 1.5rem;
  display: flex;
  justify-content: space-between; /* <-- This along with flex-direction will do that for you */
  flex-direction: column;
}
```

#### 2. Remove `display: block;` from everything except the `img` css. you don't need it, it breaks the grid. 

#### 3. Don't use `<hr>` tags, they are for dividing chunks of text copy such as book chapters, not decoration. They are not accessibility friendly when used for decorations. Use border-top or border-bottom instead. 
```
footer { 
  padding: 1rem;
  border-top: .2rem solid #e2e2e2;
  text-align: center;
}
```

#### 4. 
```
header {   /* use display-flex here */

  /* text-align: center; REMOVE   */
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 1rem .5rem;
}
```

#### 5.  Treat the h1 as its own container. This can only be done with an h1

```
h1 { 
  /* margin: 0; REMOVE */
  display: flex;
  flex-direction: column;
  align-items: center;
  font-size: 2rem;
  margin: 0;
  padding: 0 1rem;
}
```
In your media query : 
```

@media only screen and (min-width: 38em) {


  h1 {
    align-items: flex-start;  /*Align the logo to the left on medium screen*/
  }
```

#### 6. Add padding to `nav li` items
```
nav li {
  padding: 0 .5em;
}
```

This will likely not fix the weird screenshot issue, but make these fixes and check in.

**Comment by bensullivan8** [comment]
Thanks for the help with that, @hellachella. I implemented all those recommendations and it seems to have done the trick for making it look more accurate. Although, as predicted, it did not fix the Markbot issue. 
I found step 5 interesting with how you can only do that with an H1... why is that? Why wouldn't it be made so it would work with any heading style text?
Again, thanks for your help!

**Comment by hellachella** [comment]
Because it can stand in place of/beside a header.

**Comment by hellachella** [comment]
Commit your latest changes and tag me. I will download it again. I am wracking my brain about why Markbot can't see it. I thought I was for sure the display: block. I'll mess around with it.

**Comment by bensullivan8** [comment]
Okay, thanks @hellachella. My latest changes have already been committed and everything is pushed.

**Comment by bensullivan8** [comment]
Yeah, it's gotta be something wrong with Markbot because now on my Kraken Good Accessibility assignment it won't even complete loading after I try to check my repo file. I've let it sit and load for about an hour now and the gears are still turning. So I don't know what to do here. I've restarted and shut down my computer multiple times and everything else about my computer works fine, except Markbot. It's quite frustrating...

**Comment by hellachella** [comment]
Kraken is doing that to everyone. I'll look into this assignment again.

**Comment by hellachella** [comment]
Once you have complete Kraken, it will likely hang in Markbot. We can work around it by sending me a screenshot of your Markbot screen and a screenshot of your code. I will submit your grade for you then.

**Comment by hellachella** [comment]
Ok, I've downloaded it and opened in browser. You have achieved the layout using CSS grid and flexbox as was the learning outcome of the assignment. I'll grade it.
